refactor: change `miniz_oxide` to `flate2` with `zlib-rs` backend (#71)
Reason for change:

* unify deflate usage across our tools
  * consistent behaviour
  * reduce compilation size
* reason for switching from miniz_oxide to zlib-rs:
  * flate2 uses simd-adler32 https://github.com/rust-lang/flate2-rs/releases/tag/1.1.3
  * simd-adler32 breaks on wasm:

```
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `std`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/simd-adler32-0.3.7/src/imp/wasm.rs:146:34
    |
146 |     let arr: [u32; 4] = unsafe { std::mem::transmute(v) };
    |                                  ^^^ use of unresolved module or unlinked crate `std`
    |
    = help: if you wanted to use a crate named `std`, use `cargo add std` to add it to your `Cargo.toml`
help: consider importing this module
    |
 27 +   use core::mem;
    |
help: if you import `mem`, refer to it directly
    |
146 -     let arr: [u32; 4] = unsafe { std::mem::transmute(v) };
146 +     let arr: [u32; 4] = unsafe { mem::transmute(v) };
    |

```